name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          go generate ./...
          go build -v .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt install ffmpeg -y

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          mkdir ./coverage
          go test -race -coverprofile=./c.out -covermode=atomic -v ./...
          go run github.com/jandelgado/gcov2lcov -infile=c.out -outfile=coverage/lcov.info

      - name: Upload coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
